Controllers/CupcakesController.cs
using CupcakeEntity.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace CupcakeEntity.Controllers
{
    public class CupcakesController : Controller
    {

        // refernces DBSet in Identity Models
        private  ApplicationDbContext context;

        public CupcakesController()
        {
            context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            context.Dispose();
        }

        // GET: Cupcakes
        public ActionResult Index()
        {
            List<CupcakeModel> cupcakes = context.Cupcakes.ToList();

            return View("Index", cupcakes);
        }

        //public ActionResult Index(string sortOrder)
        //{
         //   ViewData["NameSort"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
          //  var cupcakes = from s in context.Cupcakes
         //                  select s;
         //   switch (sortOrder)
          //  {
         //       case "Name":
          //          cupcakes = cupcakes.OrderByDescending(s => s.Name);
          //          break;

          //  }

          //  var c = cupcakes.ToList();

          //  return View("Index", c);

        //}

        public ActionResult Details(int id)
        {
            CupcakeModel cupcake = context.Cupcakes.SingleOrDefault(c => c.Id == id);

            return View("Details", cupcake);        
        }


        public ActionResult Create()
        {

            return View("CupcakeForm", new CupcakeModel());
        }

        public ActionResult Edit(int id)
        {
            CupcakeModel cupcake = context.Cupcakes.SingleOrDefault(c => c.Id == id);

            return View("CupcakeForm", cupcake);
        }

        public ActionResult Delete(int id)
        {
            CupcakeModel cupcake = context.Cupcakes.SingleOrDefault(c => c.Id == id);

            context.Entry(cupcake).State = EntityState.Deleted;

            context.SaveChanges();

            return Redirect("/Cupcakes");
        }

        public ActionResult ProcessCreate(CupcakeModel cupcakeModel)
        {
            CupcakeModel cupcake = context.Cupcakes.SingleOrDefault(c => c.Id == cupcakeModel.Id);

            // Edit
            if (cupcake != null)
            {

                cupcake.Name = cupcakeModel.Name;
                cupcake.Price = cupcakeModel.Price;
                cupcake.DateCreated = cupcakeModel.DateCreated;
                cupcake.DateModified = cupcakeModel.DateModified;

            }

            // new item
            else
            {
                context.Cupcakes.Add(cupcakeModel);
            }

            context.SaveChanges();

            return View("Details", cupcakeModel);
        }


        public ActionResult SearchForm()
        {

            return View("SearchForm");
        }

        public ActionResult SearchForName(string searchPhrase)
        {
            var cupcakes = from c in context.Cupcakes where c.Name.Contains(searchPhrase) select c;

            return View("Index", cupcakes);
        }
    }
}

Views/Cupcakes/CupcakeForm.cshtml
@model CupcakeEntity.Models.CupcakeModel

@{
    ViewBag.Title = "CupcakeForm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<p></p>
<p></p>
<h2>Cupcake Form</h2>


@using (Html.BeginForm("ProcessCreate", "Cupcakes"))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">

    <hr />

    <h4>Create Your Own Cupcake</h4>

    <p></p>
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group" style="color:#485785">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <p></p>
    <div class="form-group" style="color:#485785">
        @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>

    <p></p>
    <div class="form-group" style="color:#485785">
        @Html.LabelFor(model => model.DateCreated, "Date Created", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DateCreated, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DateCreated, "", new { @class = "text-danger" })
        </div>
    </div>

    <!-- <div class="form-group">
        @Html.LabelFor(model => model.DateModified, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DateModified, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DateModified, "", new { @class = "text-danger" })
        </div>
    </div> -->

    <input type="hidden" name="Id" value="@Model.Id" />

    <p></p>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10" style="color:#485785">
            <input style="color:#485785" type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<p></p>
<div class="btn btn-default btn-sm">@Html.ActionLink("Back to List", "Index")</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Cupcakes/Details.cshtml
@model CupcakeEntity.Models.CupcakeModel

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<p></p>
<p></p>
<h2>Details of @Html.DisplayFor(model => model.Name)</h2>

<div>
    <!-- <h4>CupcakeModel</h4> -->
    <hr />
    <dl class="dl-horizontal" style="color:#485785">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            $@Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateCreated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateModified)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateModified)
        </dd>

    </dl>
</div>
<p>
    <div class="btn btn-default btn-sm">@Html.ActionLink("Edit", "Edit", new { id = Model.Id })</div>
    |
    <div class="btn btn-default btn-sm">@Html.ActionLink("Back to List", "Index")</div>
    
</p>

Views/Cupcakes/Index.cshtml
@model IEnumerable<CupcakeEntity.Models.CupcakeModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<p></p>
<p></p>
<h2>My Cupcakes!</h2>

<p>

    <div class="btn btn-default">@Html.ActionLink("Create New", "Create")</div>

    
</p>
<table class="table table-group-divider" style="color:#485785">
    <tr style="border-bottom:1px solid #485785">
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateCreated)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateModified)
        </th>
        <th></th>
    </tr>


    @if (Model.Any())
    {
        foreach (var item in Model)
        {
            <tr style="border-bottom:1px solid #485785">
                <td>
                    <div class="btn btn-default btn-sm">@Html.ActionLink(item.Name, "Details", new { id = item.Id }) </div>
                </td>
                <td>
                    $@Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateCreated)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateModified)
                </td>
                <td>
                    <div class="btn btn-default btn-sm">@Html.ActionLink("Edit", "Edit", new { id = item.Id })</div>
                    |
                    <div class="btn btn-default btn-sm">@Html.ActionLink("Details", "Details", new { id = item.Id }) </div>
                    |
                    <div class="btn btn-default btn-sm">@Html.ActionLink("Delete", "Delete", new { id = item.Id })</div>
                </td>


            </tr>

        }
    }
     else
     {
        
        <tr>
            <td class="h3">
                <p></p>
                <p></p>
                No Cupcakes found.
            </td>
        </tr>
     }




</table>

<p></p>
<div class="btn btn-default btn-sm">@Html.ActionLink("Back to List", "Index")</div>

Views/Cupcakes/SearchForm.cshtml
@model CupcakeEntity.Models.CupcakeModel

@{
    ViewBag.Title = "SearchForm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<p></p>
<p></p>
<h2>Search Form</h2>


@using (Html.BeginForm("SearchForName","Cupcakes")) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CupcakeModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="col-md-10">

                <label for="searchPhrase" class="h6">Search Name</label>
                <input type="text" name="searchPhrase" id="searchPhrase" class="form-control" />

            </div>
        </div>

        
        <p></p>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input style="color:#485785" type="submit" value="Search" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<p></p>
<a class="btn btn-default btn-sm" href="~/cupcakes">Back to List</a>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}